### ISSUE TITLE
Failed to execute goal

### ISSUE THREAD

**Issue by marlonlom** [alexnederlof/Jasper-report-maven-plugin#35]
Greetings, 

I've followed the plugin configuration in my jasperreports project pom, when I do mvn clean install, i'm having this error message when executing the plugin in my project: 

Failed to execute goal com.alexnederlof:jasperreports-plugin:2.0:jasper (default) on project: 
Error while compiling Jasper reports: java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException: org.codehaus.groovy.control.CompilationFailedException -> [Help 1]

Any ideas for knowing whats going on?

Regards

**Comment by alexnederlof** [comment]
No idea, sorry. I don't work with this plugin myself anymore. I just Keep track of pull requests others make and push new versions.

**Comment by brunoabdon** [comment]
@marlonlom , your reports are using [Groovy](http://www.groovy-lang.org/) as the scripting language. This has been the default for reports created with iReport since some version.

To resolve this, add the Groovy dependency to your plugin:

          <plugin>
	            <groupId>com.alexnederlof</groupId>
	            <artifactId>jasperreports-plugin</artifactId>
	            <version>1.9</version>

     		    <dependencies>
			  <dependency>
			      <groupId>org.codehaus.groovy</groupId>
			      <artifactId>groovy-all</artifactId>
			      <version>1.5.8</version>
			   </dependency>		
                    </dependencies>
           //...
          </plugin>

This is not, in itself, an but in the plugin. I suggest this issue to be closed as invalid.

**Comment by alexnederlof** [comment]
Thanks @brunoabdon
